### PR TITLE
Add support for multiple tags

### PR DESCRIPTION
**Pull request by karl82**
I want to be able to move notes based on multiple tags. Example

project&archive => _archived/projects
project => projects

Tag suggestion works too.

I've tested it locally

### CODE REVIEW

**Comment by Hugo-COLLIN** [comment]
@karl82 Tested it on a test vault and it doesn't work for me.
Do you enable "Use regular expression to check for tags" ?
I tried `a&b` , `#a&#b`, `a,b`, `#a,#b`.

**Comment by Hugo-COLLIN** [comment]
@farux You should review this branch, it's a really wanted feature.

Note: Works with comma-separated #tags, only with "Use regular expression to check for tags" disabled.

Example: `#tag1,#tag2`

**Comment by Hugo-COLLIN** [comment]
@karl82 Found a bug: when adding a second tag from suggestion (pressing enter), the first tag is passing to lower case, so it breaks the matching.

**Comment by Hugo-COLLIN** [comment]
@karl82  Your changes also break the filename matching

**Comment by karl82** [comment]
> Your changes also break the filename matching

@Hugo-COLLIN Do you have example?

**Comment by karl82** [comment]
> Found a bug: when adding a second tag from suggestion (pressing enter), the first tag is passing to lower case, so it breaks the matching.

@Hugo-COLLIN I will look into this later. It's been 6 months since I wrote this code.

**Pull request closed without merging**
